### PR TITLE
Windows 10 App Essentials 21.02

### PR DESCRIPTION
**Pull request by josephsl**
Hi,

First Add-on Store test add-on: Windows 10 App Essentials 21.02.

Changelog:

* Requires Windows 10 Version 2004 (May 2020 Update/build 19041) or later.
* Initial support for updated emoji panel (Input Experience Panel) in build 21296 or later.

Few notes:

* This is a test add-on store submission designed to test store Json schema. A corresponding pull request will be sent to Add-on Files repository (traditional add-on update submission).
* Json file is named without a patch variable to see if major.minor.0 will be same as major.minor to keep compatibility in mind.
* An additional field, "MinWindowsVersion" was added to specify the minimum Windows version required to use the add--on, containing three integers recording Windows major version, minor version, and build. I don't expect many add-ons to use this field, therefore it can be treated as optional but could be helpful when looking for add-on updates for a specific Windows release. Of my add-ons, only Windows 10 App Essentials and Enhanced Touch Gestures will use these fields (the former due to Windows as a Service, the latter due to touchscreen support in Windows 8 and later).
* SHA256 value is stored as a lowercase string (64 hexadecimal characters).

Thanks.

### CODE REVIEW

**Comment by josephsl** [comment]
Hi,

For others submitting pull requests: you don't have to create "addons" folder as this PR does it for you. Therefore please wait until this PR is accepted before adding test (and real) add-on releases.

Tanks.

**Comment by nvdaes** [comment]
What's the purpose of this PR? Can be useful for testing, even when the `NVDA-Addon-submission` repository mentioned in PR #6 with the addon_release.json template is not created, and given that the current repo is being used to decide and document the process?
Just seeing it now 😄

**Comment by feerrenrut** [comment]
@nvdaes I'll fixup the name of the repo used in #6, I'll also add a PR review checklist. Hopefully the steps in the review process can be automated. Anyone with experience building github workflows willing to help with that? If we can automate all the checks, then the process will become very smooth. This PR #7 can be used as a testing ground for the process.

**Comment by nvdaes** [comment]
Hi, @mhameed and me built some workflows available at

https://github.com/nvdaaddons/l10ntest

After that I improved some of them for real usage in my add-ons. I
will help as possible. We can play with this PR adding workflows when
the checklist is available.

2021-02-08 11:13 GMT+01:00, Reef Turner <notifications@github.com>:

**Comment by josephsl** [comment]
Hi,

Updating the PR to include latest JSON schema, it will still be Windows 10 App Essentials 21.02 (add-on will be renamed to Windows App Essentials once the Store is up).

Thanks.

**Review by nvdaes — COMMENTED** [review]
This has fields not included in the schema related to Windows version:

- Is this allowed in the json file?
- Would be a way to deal with this extra metadata¿
Cheers

**Comment by josephsl** [comment]
Hi, I would treat them as optional and let the add-on handle it as part of its install tasks. Thanks.

**Comment by nvdaes** [comment]
Hope this can be clarified. I'm not sure if optional fields should be placed in the jsonfile or if advantages are greater than drawbacks.
For example, if this is used in a server, the number of expected fields may or not be important for people making requests if they implement some rules to see if the expected metadata is valid. I think this should be documented in case it's allowed. For installTasks maybe enough the manifest.ini.

🤔

**Comment by nvdaes** [comment]
Also, since this PR is a sample and subject to comments, I read something about the possibility of using, for example, some kind of form (The idea comes from Reef, I think). This morning I"ve fixed an issue form and as a suggestion, now that issue forms are present on Github, I wonder if this PR or others can be sent via an issue, for authors not wishing to for this repo. For example, authors may fill in an issue form with addon name and other fields and GitHub Actions may create the PR. I"m also interested in this, for example, to make easier to contribute a website on GitHub Pages. But I haven"t tested it. Just to provide several options. I"ll test and will come with feedback if results are successfull.

Enviado desde mi iPhone

**Comment by nvdaes** [comment]
Hello, since @Josephsl tested in this PR including optional fields not
mentioned in jsonschema, I assume this is not definitive, so I've
tested with issue forms.
I have confirmed that a PR can be created with GitHub Actions from an
issue. I've created a PR in my fork of this repo with GitHub Actions
triggered by issue event. For testing, I have made that GH Actions
push to a new branch of my fork and create a pr with GH CLI, installed
in gitHub servers, ready to be use in GitHub Actions. The new branch
contains a new directory named test with the issue body. I think that,
if this approach is adopted, the json file maybe created from the
issue body or even, certain files, from addon manifest. Though I think
it maybe better to use the issue body so that authors fill in it
properly. A review meybe performed and manu8ally and with the validate
addon metadata action or whatever. And a person with triage role may
label the issue to trigger the event to create the PR.
Different templates maybe created, to add or remove add-ons.
Just thinking. If I should try to create a json file for testing let me know.

2021-07-04 9:42 GMT+02:00, nvdaes ***@***.***>:
> Also, since this PR is a sample and subject to comments, I read something
> about the possibility of using, for example, some kind of form (The idea
> comes from Reef, I think). This morning I"ve fixed an issue form and as a
> suggestion, now that issue forms are present on Github, I wonder if this PR
> or others can be sent via an issue, for authors not wishing to for this
> repo. For example, authors may fill in an issue form with addon name and
> other fields and GitHub Actions may create the PR. I"m also interested in
> this, for example, to make easier to contribute a website on GitHub Pages.
> But I haven"t tested it. Just to provide several options. I"ll test and will
> come with feedback if results are successfull.

>

> Enviado desde mi iPhone

>

**Comment by feerrenrut** [comment]
Hi @nvdaes, lets have the discussion about using forms on a separate issue. I think it is a good idea, but it won't be our initial focus.

Additional (not in the spec) optional fields should not be allowed in this metadata. It should cause a failure of the automated checks on the PR. The metadata stored in this repository isn't for consumption by add-ons. That said, if a developer can make a case for altering the spec, we'll consider the reasoning. Please open a PR for this.

**Comment by nvdaes** [comment]
OK

2021-07-06 7:40 GMT+02:00, Reef Turner ***@***.***>:

**Comment by feerrenrut** [comment]
For testing I have merged in the changes from PR #10

**Comment by nvdaes** [comment]
Just seeing that @feerrenrut  fixed submission.
This is great.

**Comment by feerrenrut** [comment]
Yes, this is in progress @nvdaes I am using this addon submission as an initial test.

**Comment by nvdaes** [comment]
@feerrenrut, you may also add in the yaml file, instead of:
python -m pip install --upgrade wheel

python -m pip install --upgrade pip wheel

To avoid a warning about an old version of pip.
Also, I think that the question of multiline description should be tested or just avoid long descriptions, since the help is available in HTML. And I'd like a clarification of the license that needs to be used. If it's GPL2 in all cases, maybe ommited in the .json file. I think this has been confusing in the past and it's a chance to clarify it.

**Review by feerrenrut — APPROVED** [review]
I think we can merge this in now.

**Comment by nvdaes** [comment]
I"ll try to use this add-on to attach the corresponding .json metadata file as an asset of releases for my add-ons. Thanks @Josephsl.

Enviado desde mi iPhone

**Comment by josephsl** [comment]
Hi, in turn I’ll do my best to protect this version of Windows App Essentials from being deleted as it served as a canary. Thanks.

**Comment by nvdaes** [comment]
I started writing a yaml file to download metadata. Then I thought that perfaps the addonTemplate can include a .jsonfile to be used by add-ons and maybe faster. Not sure what approach would be better. I"ll see, but attaching assets to releases maybe a good idea since they can be easily pasted or consulted.

**Pull request merged**
